fix h_malloc_wrapper integration for Cuttlefish builds
Fixes build errors:

error: frameworks/libs/native_bridge_support/android_api/libc/Android.bp:27:1: m
  odule "libnative_bridge_guest_libc" variant "android_native_bridge_arm64_armv8-a
  _static": module source path "frameworks/libs/native_bridge_support/android_api/
  libc/bionic/h_malloc_wrapper.cpp" does not exist

Test: lunch aosp_cf_x86_64_only_phone-cur-userdebug with hardened_malloc fix boots